CREATE TABLESPACE shangpin DATAFILE 
  'C:\ORACLE11G\ORADATA\ACCP11G\shangpin.DBF' SIZE 20M AUTOEXTEND OFF
LOGGING
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT MANUAL
FLASHBACK ON;

CREATE USER dfy IDENTIFIED BY "900523"
 DEFAULT TABLESPACE "SHANGPIN"
 QUOTA UNLIMITED ON "SHANGPIN";

GRANT "AQ_ADMINISTRATOR_ROLE" TO dfy WITH ADMIN OPTION;
GRANT "AQ_USER_ROLE" TO dfy WITH ADMIN OPTION;
GRANT "AUTHENTICATEDUSER" TO dfy WITH ADMIN OPTION;
GRANT "CONNECT" TO dfy WITH ADMIN OPTION;
GRANT "CSW_USR_ROLE" TO dfy WITH ADMIN OPTION;
GRANT "CTXAPP" TO dfy WITH ADMIN OPTION;
GRANT "CWM_USER" TO dfy WITH ADMIN OPTION;
GRANT "DATAPUMP_EXP_FULL_DATABASE" TO dfy WITH ADMIN OPTION;
GRANT "DATAPUMP_IMP_FULL_DATABASE" TO dfy WITH ADMIN OPTION;
GRANT "DBA" TO dfy WITH ADMIN OPTION;
GRANT "DELETE_CATALOG_ROLE" TO dfy WITH ADMIN OPTION;
GRANT "EJBCLIENT" TO dfy WITH ADMIN OPTION;
GRANT "EXECUTE_CATALOG_ROLE" TO dfy WITH ADMIN OPTION;
GRANT "EXP_FULL_DATABASE" TO dfy WITH ADMIN OPTION;
GRANT "GATHER_SYSTEM_STATISTICS" TO dfy WITH ADMIN OPTION;
GRANT "HS_ADMIN_ROLE" TO dfy WITH ADMIN OPTION;
GRANT "IMP_FULL_DATABASE" TO dfy WITH ADMIN OPTION;
GRANT "JAVADEBUGPRIV" TO dfy WITH ADMIN OPTION;
GRANT "JAVAIDPRIV" TO dfy WITH ADMIN OPTION;
GRANT "JAVASYSPRIV" TO dfy WITH ADMIN OPTION;
GRANT "JAVAUSERPRIV" TO dfy WITH ADMIN OPTION;
GRANT "JAVA_ADMIN" TO dfy WITH ADMIN OPTION;
GRANT "JAVA_DEPLOY" TO dfy WITH ADMIN OPTION;
GRANT "JMXSERVER" TO dfy WITH ADMIN OPTION;
GRANT "LOGSTDBY_ADMINISTRATOR" TO dfy WITH ADMIN OPTION;
GRANT "MGMT_USER" TO dfy WITH ADMIN OPTION;
GRANT "OEM_ADVISOR" TO dfy WITH ADMIN OPTION;
GRANT "OEM_MONITOR" TO dfy WITH ADMIN OPTION;
GRANT "OLAPI_TRACE_USER" TO dfy WITH ADMIN OPTION;
GRANT "OLAP_DBA" TO dfy WITH ADMIN OPTION;
GRANT "OLAP_USER" TO dfy WITH ADMIN OPTION;
GRANT "OLAP_XS_ADMIN" TO dfy WITH ADMIN OPTION;
GRANT "ORDADMIN" TO dfy WITH ADMIN OPTION;
GRANT "OWB$CLIENT" TO dfy WITH ADMIN OPTION;
GRANT "OWB_DESIGNCENTER_VIEW" TO dfy WITH ADMIN OPTION;
GRANT "OWB_USER" TO dfy WITH ADMIN OPTION;
GRANT "RECOVERY_CATALOG_OWNER" TO dfy WITH ADMIN OPTION;
GRANT "RESOURCE" TO dfy WITH ADMIN OPTION;
GRANT "SCHEDULER_ADMIN" TO dfy WITH ADMIN OPTION;
GRANT "SELECT_CATALOG_ROLE" TO dfy WITH ADMIN OPTION;
GRANT "SPATIAL_CSW_ADMIN" TO dfy WITH ADMIN OPTION;
GRANT "SPATIAL_WFS_ADMIN" TO dfy WITH ADMIN OPTION;
GRANT "WFS_USR_ROLE" TO dfy WITH ADMIN OPTION;
GRANT "WKUSER" TO dfy WITH ADMIN OPTION;
GRANT "WM_ADMIN_ROLE" TO dfy WITH ADMIN OPTION;
GRANT "XDBADMIN" TO dfy WITH ADMIN OPTION;
GRANT "XDB_SET_INVOKER" TO dfy WITH ADMIN OPTION;
GRANT "XDB_WEBSERVICES" TO dfy WITH ADMIN OPTION;
GRANT "XDB_WEBSERVICES_OVER_HTTP" TO dfy WITH ADMIN OPTION;
GRANT "XDB_WEBSERVICES_WITH_PUBLIC" TO dfy WITH ADMIN OPTION;
ALTER USER dfy DEFAULT ROLE "AQ_ADMINISTRATOR_ROLE", "AQ_USER_ROLE", "AUTHENTICATEDUSER", "CONNECT", "CSW_USR_ROLE", "CTXAPP", "CWM_USER", "DATAPUMP_EXP_FULL_DATABASE", "DATAPUMP_IMP_FULL_DATABASE", "DBA", "DELETE_CATALOG_ROLE", "EJBCLIENT", "EXECUTE_CATALOG_ROLE", "EXP_FULL_DATABASE", "GATHER_SYSTEM_STATISTICS", "HS_ADMIN_ROLE", "IMP_FULL_DATABASE", "JAVADEBUGPRIV", "JAVAIDPRIV", "JAVASYSPRIV", "JAVAUSERPRIV", "JAVA_ADMIN", "JAVA_DEPLOY", "JMXSERVER", "LOGSTDBY_ADMINISTRATOR", "MGMT_USER", "OEM_ADVISOR", "OEM_MONITOR", "OLAPI_TRACE_USER", "OLAP_DBA", "OLAP_USER", "OLAP_XS_ADMIN", "ORDADMIN", "OWB$CLIENT", "OWB_DESIGNCENTER_VIEW", "OWB_USER", "RECOVERY_CATALOG_OWNER", "RESOURCE", "SCHEDULER_ADMIN", "SELECT_CATALOG_ROLE", "SPATIAL_CSW_ADMIN", "SPATIAL_WFS_ADMIN", "WFS_USR_ROLE", "WKUSER", "WM_ADMIN_ROLE", "XDBADMIN", "XDB_SET_INVOKER", "XDB_WEBSERVICES", "XDB_WEBSERVICES_OVER_HTTP", "XDB_WEBSERVICES_WITH_PUBLIC";
